download_dataset:
  dataset_name: "parisrohan/credit-score-classification"
  test_csv_name: "test.csv"
  train_csv_name: "train.csv"

train:
  random_state: 42
  number_of_folds: 5
  categorical:
    - "Occupation"
    - "Type_of_Loan"
    - "Credit_Mix"
    - "Payment_of_Min_Amount"
    - "Payment_Behaviour"
  drop:
    - "ID"
    - "Customer_ID"
    - "Month"
    - "Name"
    - "SSN"

preprocessing:
  numeric_clip_quantiles:
    lower: 0.01
    upper: 0.99
  step_configs:
    - clean_func: "clean_numerical_field"
      column: "Age"
      strip: "_"
      datatype: "int64"
      min_value: 0
      max_value: 100
    - clean_func: "clean_categorical_field"
      column: "SSN"
      replace_value: "#F%$D@*&8"
    - clean_func: "clean_categorical_field"
      column: "Occupation"
      replace_value: "_______"
    - clean_func: "clean_categorical_field"
      column: "Credit_Mix"
      replace_value: "_"
    - clean_func: "clean_categorical_field"
      column: "Payment_Behaviour"
      replace_value: "!@9#%8"
  typical_numeric_columns:
    - "Annual_Income"
    - "Monthly_Inhand_Salary"
    - "Num_Bank_Accounts"
    - "Num_Credit_Card"
    - "Interest_Rate"
    - "Num_of_Loan"
    - "Delay_from_due_date"
    - "Changed_Credit_Limit"
    - "Num_of_Delayed_Payment"
    - "Num_Credit_Inquiries"
    - "Outstanding_Debt"
    - "Credit_Utilization_Ratio"
    - "Total_EMI_per_month"
    - "Amount_invested_monthly"
    - "Monthly_Balance"
