download_dataset:
  dataset_name: "parisrohan/credit-score-classification"
  test_csv_name: "test.csv"
  train_csv_name: "train.csv"

train:
  random_state: 42
  number_of_folds: 5
  categorical:
    - "Occupation"
    - "Type_of_Loan"
    - "Credit_Mix"
    - "Payment_of_Min_Amount"
    - "Payment_Behaviour"
  drop:
    - "ID"
    - "Customer_ID"
    - "Month"
    - "Name"
    - "SSN"

preprocessing:
  column_templates:
    typical_numeric: &typical_numeric
      - op: strip
        chars: "_"
      - to_numeric
      - op: bounds
        min_value: 0
      - fill_median
      - op: cast
        dtype: "float64"
  columns:
    Age:
      - op: strip
        chars: "_"
      - to_numeric
      - op: bounds
        min_value: 0
        max_value: 100
      - fill_median
      - op: cast
        dtype: "int64"
    SSN:
      - op: replace
        value: "#F%$D@*&8"
      - fill_mode
    Occupation:
      - op: replace
        value: "_______"
      - fill_mode
    Credit_Mix:
      - op: replace
        value: "_"
      - fill_mode
    Payment_Behaviour:
      - op: replace
        value: "!@9#%8"
      - fill_mode
    Annual_Income: *typical_numeric
    Monthly_Inhand_Salary: *typical_numeric
    Num_Bank_Accounts: *typical_numeric
    Num_Credit_Card: *typical_numeric
    Interest_Rate: *typical_numeric
    Num_of_Loan: *typical_numeric
    Delay_from_due_date: *typical_numeric
    Changed_Credit_Limit: *typical_numeric
    Num_of_Delayed_Payment: *typical_numeric
    Num_Credit_Inquiries: *typical_numeric
    Outstanding_Debt: *typical_numeric
    Credit_Utilization_Ratio: *typical_numeric
    Total_EMI_per_month: *typical_numeric
    Amount_invested_monthly: *typical_numeric
    Monthly_Balance: *typical_numeric
    Credit_History_Age:
      - convert_age_to_months
